import { Project, MenuItem } from '@/types'

export const PROJECTS: Project[] = [
  {
    id: 'commercial-001',
    title: 'UNIQLO SS24',
    client: 'UNIQLO',
    category: 'COMMERCIAL',
    year: 2024,
    thumbnail: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80',
    description: 'Spring/Summer 2024 Campaign featuring contemporary lifestyle.',
    credits: {
      director: 'Kazuyasu Yoshioka',
      cinematographer: 'Takeshi Yamamoto',
    },
    aspectRatio: '16:9',
    featured: true,
  },
  {
    id: 'commercial-002',
    title: 'Toyota Crown',
    client: 'Toyota',
    category: 'COMMERCIAL',
    year: 2024,
    thumbnail: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80',
    description: 'New Crown launch campaign emphasizing innovation and tradition.',
    credits: {
      director: 'Kazuyasu Yoshioka',
    },
    aspectRatio: '16:9',
    featured: true,
  },
  {
    id: 'commercial-003',
    title: 'Shiseido Beauty',
    client: 'Shiseido',
    category: 'COMMERCIAL',
    year: 2023,
    thumbnail: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&q=80',
    description: 'Beauty campaign exploring the intersection of tradition and modernity.',
    credits: {
      director: 'Kazuyasu Yoshioka',
      cinematographer: 'Yuki Tanaka',
    },
    aspectRatio: '4:3',
    featured: false,
  },
  {
    id: 'mv-001',
    title: 'Kenshi Yonezu - LADY',
    client: 'Kenshi Yonezu',
    category: 'MV',
    year: 2024,
    thumbnail: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
    description: 'Music video exploring themes of identity and transformation.',
    credits: {
      director: 'Kazuyasu Yoshioka',
      editor: 'Kenji Sato',
    },
    aspectRatio: '16:9',
    featured: true,
  },
  {
    id: 'mv-002',
    title: 'YOASOBI - Idol',
    client: 'YOASOBI',
    category: 'MV',
    year: 2023,
    thumbnail: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800&q=80',
    description: 'Animated music video blending reality with fantasy.',
    credits: {
      director: 'Kazuyasu Yoshioka',
    },
    aspectRatio: '16:9',
    featured: false,
  },
  {
    id: 'mv-003',
    title: 'King Gnu - SPECIALZ',
    client: 'King Gnu',
    category: 'MV',
    year: 2023,
    thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80',
    description: 'Dark and cinematic visual narrative.',
    credits: {
      director: 'Kazuyasu Yoshioka',
    },
    aspectRatio: '16:9',
    featured: true,
  },
  {
    id: 'jameswebb-001',
    title: 'Nocturne',
    client: 'JAMES WEBB',
    category: 'JAMES WEBB',
    year: 2024,
    thumbnail: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=800&q=80',
    description: 'An exploration of light and darkness in the cosmos.',
    credits: {
      director: 'Kazuyasu Yoshioka',
      cinematographer: 'Akira Nakamura',
    },
    aspectRatio: '16:9',
    featured: true,
  },
  {
    id: 'jameswebb-002',
    title: 'Deep Field',
    client: 'JAMES WEBB',
    category: 'JAMES WEBB',
    year: 2024,
    thumbnail: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800&q=80',
    description: 'Journey through the infinite expanse.',
    credits: {
      director: 'Kazuyasu Yoshioka',
    },
    aspectRatio: '1:1',
    featured: true,
  },
  {
    id: 'jameswebb-003',
    title: 'Pillars of Creation',
    client: 'JAMES WEBB',
    category: 'JAMES WEBB',
    year: 2023,
    thumbnail: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&q=80',
    description: 'Reimagining the birth of stars.',
    credits: {
      director: 'Kazuyasu Yoshioka',
    },
    aspectRatio: '4:3',
    featured: false,
  },
  {
    id: 'jameswebb-004',
    title: 'Event Horizon',
    client: 'JAMES WEBB',
    category: 'JAMES WEBB',
    year: 2023,
    thumbnail: 'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=800&q=80',
    description: 'At the edge of the unknown.',
    credits: {
      director: 'Kazuyasu Yoshioka',
    },
    aspectRatio: '16:9',
    featured: false,
  },
  {
    id: 'commercial-004',
    title: 'Muji Living',
    client: 'MUJI',
    category: 'COMMERCIAL',
    year: 2023,
    thumbnail: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
    description: 'Minimal living campaign.',
    credits: {
      director: 'Kazuyasu Yoshioka',
    },
    aspectRatio: '16:9',
    featured: false,
  },
  {
    id: 'commercial-005',
    title: 'Issey Miyake Pleats',
    client: 'Issey Miyake',
    category: 'COMMERCIAL',
    year: 2024,
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    description: 'Fashion film celebrating movement and form.',
    credits: {
      director: 'Kazuyasu Yoshioka',
    },
    aspectRatio: '9:16',
    featured: true,
  },
]

export const MENU_ITEMS: MenuItem[] = [
  { id: 'top', label: 'TOP', href: '/' },
  { id: 'commercial', label: 'COMMERCIAL', href: '/?category=COMMERCIAL' },
  { id: 'mv', label: 'MV', href: '/?category=MV' },
  { id: 'jameswebb', label: 'JAMES WEBB', href: '/?category=JAMES WEBB' },
  { id: 'about', label: 'ABOUT', href: '/about' },
]

export const CATEGORIES = ['ALL', 'COMMERCIAL', 'MV', 'JAMES WEBB'] as const
